import smtplib
import pandas as pd
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# Load CSV
df = pd.read_csv('custom_messages.csv')

# Gmail SMTP setup
smtp_server = 'smtp.gmail.com'
smtp_port = 587
sender_email = 'your_email@gmail.com'
app_password = 'your_app_password_here'  # Use App Password generated by google account with 2FA

# Connect to Gmail SMTP server
try:
    server = smtplib.SMTP(smtp_server, smtp_port)
    server.starttls()
    server.login(sender_email, app_password)
    print("Logged in successfully to Gmail SMTP server.")
except Exception as e:
    print(f"Failed to connect: {e}")
    exit()

# Loop over each row in CSV
for index, row in df.iterrows():
    receiver_email = row['email']
    message_text = row['message']
    
    # Create email message
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = receiver_email
    msg['Subject'] = 'Message from BuildFastWithAI'
    msg.attach(MIMEText(message_text, 'plain'))

    try:
        server.sendmail(sender_email, receiver_email, msg.as_string())
        print(f"Email sent to {receiver_email}")
    except Exception as e:
        print(f"Failed to send email to {receiver_email}: {e}")

# Close the SMTP connection
server.quit()
print("All emails processed.")
